config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope :reports do
    get :subjects, to: 'reports#subjects', :as => 'report_subjects'
  end

  resources :students do
    get :subjects
  end

  resources :teachers do
    get :subjects
  end

  get :visitors, to: 'visitors#index'

  root to: 'visitors#index'
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :participations, dependent: :destroy
  has_many :subject_item_notes, dependent: :destroy
  has_many :subject_items, through: :participations
  accepts_nested_attributes_for :subject_items

  validates :first_name, :last_name, presence: true
end

app/models/subject_item.rb
class SubjectItem < ActiveRecord::Base
  has_many :participations, dependent: :destroy
  has_many :students, through: :participations
  has_many :subject_item_notes
  belongs_to :teacher

  validates :title, presence: true

  scope :not_assigned_or_assigned_to_teacher, -> (teacher) { where('teacher_id IS ? or teacher_id = ?', nil, teacher) }
end

app/models/subject_item_note.rb
class SubjectItemNote < ActiveRecord::Base
  belongs_to :student
  belongs_to :subject_item

  validates :student_id, :subject_item_id, presence: true

  scope :for_subject_item, -> (subject_item) { where(subject_item: subject_item) }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :rememberable

  validates :email, format: { with: Devise::email_regexp }
  validates :password, presence: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!

  expose(:students)
  expose(:student, attributes: :student_params)
  expose(:student_subject_items) { student.subject_items }

  def create
    if student.save
      redirect_to student_path(student), notice: I18n.t('shared.created', resource: 'Student')
    else
      render :new
    end
  end

  def update
    if student.save
      redirect_to student_path(student), notice: I18n.t('shared.updated', resource: 'Student')
    else
      render :edit
    end
  end

  def destroy
    student.destroy
    redirect_to students_path, notice: I18n.t('shared.deleted', resource: 'Student')
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :birthdate, :subject_item_ids => [])
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!

  expose(:teachers)
  expose(:teacher, attributes: :teacher_params)
  expose(:teacher_subject_items) { teacher.subject_items }
  expose(:subject_items)

  def create
    if teacher.save
      redirect_to teacher_path(teacher), notice: I18n.t('shared.created', resource: 'Teacher')
    else
      render :new
    end
  end

  def update
    if teacher.save
      redirect_to teacher_path(teacher), notice: I18n.t('shared.updated', resource: 'Teacher')
    else
      render :edit
    end
  end

  def destroy
    teacher.destroy
    redirect_to teachers_path, notice: I18n.t('shared.deleted', resource: 'Teacher')
  end

  private

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :academic_title, subject_item_ids: [])
  end
end

app/views/reports/_subject_item.html.haml
.title
  = subject_item.decorate.title_with_assigned_teacher
%table.table.table-condensed
  %thead
    %tr
      %th.full-name= t('subjects.columns.full_name')
      %th.avg-notes= t('subjects.columns.avg_notes')
      %th.birthdate= t("subjects.columns.birthdate")
  %tbody
    - subject_item.students.each do |student|
      %tr
        %td= student.decorate.full_name
        %td= student.decorate.avg_notes(subject_item)
        %td= student.birthdate.strftime('%Y-%m_%d') if student.birthdate

app/views/reports/subjects.html.haml
- breadcrumb :subjects
.subjects
  list of subjects:
  - subject_items.each do |subject_item|
    .subject-item
    = render 'subject_item', subject_item: subject_item

app/views/students/_form.html.haml
= simple_form_for student do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :birthdate, as: :date, start_year: Date.today.year - 90
  = f.association :subject_items, label_method: :title, value_method: :id, label: 'Subject Items', as: :check_boxes
  = link_to t('shared.back'), students_path, class: 'btn btn-default'
  = f.button :submit

app/views/students/_student.haml
%tr
  %td= student.first_name
  %td= student.last_name
  %td= student.birthdate
  %td
    = link_to student_path(student), { title: t('shared.show') } do
      %button.btn.btn-default
        = fa_icon "search"
    = link_to edit_student_path(student), { title: t('shared.edit') } do
      %button.btn.btn-default
        = fa_icon "edit"
    = link_to student_path(student), { method: :delete, title: t('shared.delete') } do
      %button.btn.btn-default
        = fa_icon "times"
    = link_to student_subjects_path(student), { title: t('shared.show_subject_items') } do
      %button.btn.btn-default
        = fa_icon "list"

app/views/students/index.html.haml
- breadcrumb :students
= link_to t('shared.add_new_item'), new_student_path, class: 'btn btn-default'
%table.table.table-condensed
  %thead
    %tr
      %th= t('student.columns.first_name')
      %th= t('student.columns.last_name')
      %th= t("student.columns.birthdate")
      %th= t('shared.actions')
  %tbody
    = render students

app/views/students/show.html.haml
- breadcrumb :student, student
%table.table.table-condensed
  %tbody
    %tr
      %td= "#{t('student.columns.first_name')}:"
      %td= student.first_name
    %tr
      %td= "#{t('student.columns.last_name')}:"
      %td= student.last_name
    %tr
      %td= "#{t('student.columns.birthdate')}:"
      %td= student.birthdate

= link_to t('shared.back'), students_path, class: 'btn btn-default'